
version: '3.8'
services:
  app-blue:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: nextjs-app-blue
    container_name: nextjs-app-blue
    restart: always
    ports:
      - "3001:3000"

  app-green:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: nextjs-app-green
    container_name: nextjs-app-green
    restart: always
    ports:
      - "3002:3000"

  next-nginx:
    image: nginx:latest
    container_name: next-nginx-prod
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/prod/prod.conf:/etc/nginx/conf.d/default.conf
