

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: nextjs-app
    container_name: nextjs-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    

  nginx:
    image: nginx:latest
    container_name: nginx-dev
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
